name: Deploy via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sftp_host:       { description: "Override SFTP host", required: false, type: string }
      sftp_port:       { description: "Override SFTP port", required: false, type: string }
      sftp_username:   { description: "Override SFTP username", required: false, type: string }
      sftp_password:   { description: "Override SFTP password", required: false, type: string }
      sftp_private_key:{ description: "Override SFTP SSH key", required: false, type: string }
      sftp_remote_dir: { description: "Override remote dir", required: false, type: string }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='deploy/' \
            ./ deploy/

      - name: Upload site via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:           ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sftp_host        || secrets.SFTP_HOST }}
          username:         ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sftp_username    || secrets.SFTP_USERNAME }}
          # Use ONE auth method:
          password:         ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sftp_password    || secrets.SFTP_PASSWORD }}
          ssh_private_key:  ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sftp_private_key || secrets.SFTP_SSH_PRIVATE_KEY }}
          port:             ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sftp_port        || secrets.SFTP_PORT || '22' }}
          local_path:       "deploy/*"
          remote_path:      ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sftp_remote_dir  || secrets.SFTP_REMOTE_PATH }}
          sftp_only:        true
          delete_remote_files: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
